server:
  port: 8020
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 192.168.1.79:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        #ephemeral: false # permanent instance