spring:
  config:
    import: "nacos:user-service"
  cloud:
    nacos:
      server-addr: 192.168.1.79:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
        namespace: dev
      config:
        group: DEFAULT_GROUP
        namespace: dev