spring:
  config:
    import: "nacos:inventory-service-dev.yaml"
  cloud:
    nacos:
      server-addr: 192.168.1.79:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
        namespace: public
      config:
        group: DEFAULT_GROUP
        namespace: public